- name: Install packages on Linux
  package:
    name: "{{ common_packages }}"
    state: present
  when: ansible_os_family != "AIX"

- name: Install packages on AIX
  raw: "echo Installing packages on AIX"
  loop: "{{ common_packages }}"
  when: ansible_os_family == "AIX"
