- name: Full infrastructure deployment
  hosts: all
  become: true

  roles:
   - { role: common, tags: ["baseline"] }
   - { role: users, tags: ["users"] }
   - { role: security, tags: ["security"] }
